#!/usr/bin/env bash
#
# update-license.sh — prepend the Apache 2.0 license header to every
# code + test file in the repo. Idempotent: a file that already has the
# header (detected by the marker "Apache License, Version 2.0" inside
# the leading comment block) is left alone unless `--force` is passed.
#
# Usage:
#   scripts/update-license.sh           # add where missing
#   scripts/update-license.sh --force   # also re-prepend on files that
#                                       # already have one (use after
#                                       # editing the header template
#                                       # below)
#
# Covers:
#   - Sources/**/*.swift
#   - Tests/**/*.swift
#   - scripts/*.sh
#   - .github/scripts/**/*.{sh,py}
#
# Skipped (by design):
#   - Sources/MetalTileSwift/Generated/*  — auto-regenerated by
#                                            `tile build --emit`; any
#                                            header we add gets blown
#                                            away on the next regen.
#   - Tests/Resources/                    — fixtures, not code.
#   - Any file under a `.git/` directory.
#   - Markdown (.md), YAML (.yml/.yaml), JSON (.json), TOML (.toml) —
#     license is conveyed by the repo-level LICENSE file.
#
# Comment style is per-language:
#   .swift      → //
#   .sh / .py   → #
#
# Shebang preservation: for shell + python files, the shebang on line 1
# (if present) stays first and the license header is inserted after it.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

FORCE=0
if [ "${1:-}" = "--force" ]; then
    FORCE=1
fi

# ─── License text (single canonical source) ──────────────────────────
read -r -d '' LICENSE_TEXT <<'EOF' || true
Copyright 2026 Eric Kryski (@ekryski)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
EOF

MARKER="Apache License, Version 2.0"

# Print the license formatted for the given comment prefix.
print_header() {
    local prefix="$1"
    while IFS= read -r line; do
        if [ -z "$line" ]; then
            printf "%s\n" "$prefix"
        else
            printf "%s %s\n" "$prefix" "$line"
        fi
    done <<< "$LICENSE_TEXT"
}

# Test whether the first ~40 lines of $1 already contain the marker.
has_license() {
    local file="$1"
    head -n 40 "$file" 2>/dev/null | grep -qF "$MARKER"
}

# Strip an existing license block from the top of $1 in-place. Removes
# the contiguous run of comment lines at the file's top (after an
# optional shebang) only when those lines contain the marker.
strip_existing() {
    local file="$1"
    local comment_prefix="$2"
    local tmp
    tmp="$(mktemp)"
    awk -v prefix="$comment_prefix" -v marker="$MARKER" '
        BEGIN { state = "scan_shebang"; saw_marker = 0; block_buf = "" }
        state == "scan_shebang" {
            if (NR == 1 && $0 ~ /^#!/) { print; next }
            state = "in_block"
        }
        state == "in_block" {
            # Treat a line as part of the comment block if it starts
            # with the prefix (or is just the prefix on its own, or
            # blank). We accumulate until we see the first non-comment
            # line, then decide whether to drop the block.
            line = $0
            if (substr(line, 1, length(prefix)) == prefix \
                || line == prefix \
                || (substr(line, 1, length(prefix)+1) == prefix " ") \
                || (length(line) == 0)) {
                block_buf = block_buf line "\n"
                if (index(line, marker) > 0) saw_marker = 1
                next
            }
            # Hit the first non-comment line.
            if (saw_marker) {
                # Drop the block entirely; also eat a single trailing
                # blank if it directly follows the stripped block (the
                # block accumulator already captured any blanks inside
                # the block).
            } else {
                printf "%s", block_buf
            }
            state = "passthrough"
        }
        state == "passthrough" { print; next }
        { print }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
}

# Add header to one file, respecting --force and language comment style.
process_file() {
    local file="$1"
    local prefix="$2"

    if has_license "$file"; then
        if [ "$FORCE" -ne 1 ]; then
            return 0
        fi
        strip_existing "$file" "$prefix"
    fi

    local tmp
    tmp="$(mktemp)"
    local first_line
    first_line="$(head -n 1 "$file" 2>/dev/null || true)"

    # Preserve shebang on line 1 if present (sh / py).
    if [[ "$first_line" == "#!"* ]]; then
        printf "%s\n" "$first_line" > "$tmp"
        printf "%s\n" "$prefix" >> "$tmp"
        print_header "$prefix" >> "$tmp"
        printf "%s\n" "$prefix" >> "$tmp"
        tail -n +2 "$file" >> "$tmp"
    else
        print_header "$prefix" > "$tmp"
        printf "%s\n" "$prefix" >> "$tmp"
        # Preserve original mtime by piping into the body
        cat "$file" >> "$tmp"
    fi
    mv "$tmp" "$file"
    echo "  + $file"
}

# ─── File discovery ──────────────────────────────────────────────────
# git ls-files keeps us safe — only tracked + untracked-but-not-ignored
# files are visited, never anything under .git/ or other ignored paths.
SWIFT_FILES=$(git ls-files \
    -- 'Sources/**/*.swift' 'Tests/**/*.swift' \
    ':(exclude)Sources/MetalTileSwift/Generated/*' \
    ':(exclude)Tests/Resources/*')
SH_FILES=$(git ls-files \
    -- 'scripts/*.sh' '.github/scripts/**/*.sh')
PY_FILES=$(git ls-files \
    -- '.github/scripts/**/*.py')

echo "→ Adding Apache 2.0 license headers (force=$FORCE)"

if [ -n "$SWIFT_FILES" ]; then
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        process_file "$file" "//"
    done <<< "$SWIFT_FILES"
fi

if [ -n "$SH_FILES" ]; then
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        process_file "$file" "#"
    done <<< "$SH_FILES"
fi

if [ -n "$PY_FILES" ]; then
    while IFS= read -r file; do
        [ -n "$file" ] || continue
        process_file "$file" "#"
    done <<< "$PY_FILES"
fi

echo "✓ done"
